adobe/aem-upload

README.md, src/constants.js, src/direct-binary-upload-options.js, src/direct-binary-upload-process.js, src/error-codes.js, src/file-upload-result.js, src/http-result.js, src/http-utils.js, src/part-upload-result.js, src/upload-result.js, src/utils.js, test/direct-binary-upload-process.test.js, test/direct-binary-upload.test.js, test/http-utils.test.js, test/mock-request.js, test/utils.test.js
I've updated the library so that it implements a "backoff" retry strategy when it comes to failed HTTP requests.
If a request fails, the process will delay for a specified amount of time before resubmitting the request a specified number of times. Both values are configurable, but the default retry count is 3 with a delay of 5 seconds. Each time the process retries the request, it will increase the delay.
As an example, an error scenario with the default values might look like this:
* Submit HTTP request, which fails with an error code.
* Wait 5 seconds.
* Submit HTTP request, which again fails with an error code.
* Wait 10 seconds.
* Submit HTTP request, which again fails with an error code.
* Process discontinues and reports the last error. If the retry count were higher, then the delay …
=> add functionality for retrying failed HTTP requests

README.md, src/direct-binary-upload-process.js, test/direct-binary-upload-process.test.js, test/mock-request.js
Internal code was incorrectly sending a cumulative value instead of an individual chunk length. This only applies when uploading local files.
https://github.com/adobe/aem-upload/issues/8
File upload progress was being incorrectly reported when uploading local files. Uploading in a browser context was working as expected.
Added new unit tests, verified that existing unit tests pass, and manually ensured that the transferred value is correct.
=> Transfer progress

src/direct-binary-upload-options.js, src/utils.js, test/direct-binary-upload-options.test.js, test/direct-binary-upload-process.test.js, test/utils.test.js
Whenever the upload processes uses the `URL` provided in the `withUrl()` method, it will trim any trailing forward slashes from the end of the value.
https://github.com/adobe/aem-upload/issues/7
The library should be resilient enough that it can handle URLs that end with a slash. When used in a browser context in particular, this type of value may be given to the library if the browser's address path ends with a slash.
Added new unit tests to cover the case, and verified that existing unit tests continue to pass. In addition, ran manual tests by passing trailing slashes to the upload process.
=> correctly handle upload URLs that have a trailing forward slash.

package-lock.json, src/init-response.js, test/init-response.test.js
The `completeURI` value provided by the init servlet is not URI encoded. This causes a failure in the upload process when the URI contains characters that _should_ be encoded. The fix is to use `encodeURI()` on the value before sending an HTTP request to the URL.
#11 
Fixes a bug preventing assets from being uploaded to certain directories.
1. Manually reproduce the issue using most current version of the library.
1. Created a unit test that would cause the same failure.
1. Fixed the issue.
1. Attempted to manually reproduce issue and observed that the failure no longer occurred.
1. Verified that newly created unit test passed.
N/A
=> Fix error when uploading to directories containing characters that require URL encoding

src/filesystem-upload.js, src/utils.js, test/filesystem-upload.test.js, test/mock-request.js, test/utils.test.js
Resolution to issue #14, where the library should use the assets api when creating folders instead of using the sling post servlet.
#14 
There are some cases where using the sling post servlet to create folders can cause issues with the name of the folder. Using the assets api is the recommended approach for creating asset folders in AEM.
Extended unit tests to verify the new creation method. Ran tests using a cloud AEM instance:
* Used a directory that didn't exist and verified that it was created.
* Used a directory that already existed and verified that there were no errors.
* Used /content/dam as the directory and verified the upload succeeded.
N/A
=> use the assets api to create folders

src/filesystem-upload.js, src/utils.js, test/filesystem-upload.test.js, test/utils.test.js
Added functionality to the file upload feature so that the target AEM folder, and all of its ancestors, are created if they don't exist.
#13 
Sometimes consumer may want to upload to folders that don't exist yet. Rather than requiring them to create the folders beforehand, the tool will now create them automatically.
* Added unit tests for the new feature.
* Uploaded to a folder that already exists.
* Uploaded to a folder whose ancestors already exist.
* Uploaded to a folder whose ancestors did not already exist.
N/A
=> Create folder structure

package-lock.json, package.json, src/direct-binary-upload-options.js, src/direct-binary-upload-process.js, src/filesystem-upload.js, src/http-utils.js, test/direct-binary-upload-options.test.js, test/http-utils.test.js
This is a resolution to #17. The library will now use any cookies provided in the `set-cookie` header of server responses.
See #17.
Per the ticket, there are cases where the target container may change part way through multiple file uploads. This fix will support "sticky" sessions, which should ensure that the target container remains the same through the upload process.
* Added new unit tests to cover case.
* Manually uploaded files from the command line to ensure the process still works.
N/A
=> set cookies specified by server to allow sticky sessions.

.github/workflows/node.js.yml, package.json, src/batch-manager.js, src/exports.js, src/filesystem-upload.js, src/fs-promise.js, src/http/http-client.js, src/utils.js, test/exports.test.js, test/utils.test.js
The library needs to support some very old versions of Node.js. This PR adds those versions to the testing actions that run on commits. It also fixes some incompatibility issues with the older versions.
N/A
The library is used by AEM desktop, which (for reasons we won't get into here) must run on older versions of node.js. The library must support these older versions so that it can be used by the app.
Locally ran unit tests on the older versions of node.js.
N/A
=> update compatibility for older node versions.

README.md, src/file-upload-result.js, src/filesystem-upload-options.js, src/filesystem-upload.js, test/filesystem-upload-options.test.js, test/filesystem-upload.test.js
See #40 for a description of the requested feature.
This PR provides an implementation by allowing an additional parameter on `FileSystemUpload.upload()`. This new parameter contains a simple object, whose properties can match any of the properties defined for an upload file (i.e. `createVersion`, `versionComment`, etc). These properties will be applied to each file that is uploaded.
#40 
The tool currently doesn't provide a way to specify how conflicts are handled. Some consumers may wish for a certain behavior when uploading the same asset more than once.
Added new unit tests, and verified that the options are honored when multiple files are uploaded. Verified that versions are created and that they have the appropriate values.
N/A
=> add the ability to specify upload file information when doing file system uploads

e2e/filesystem-upload.test.js, package-lock.json, package.json
Updates to the latest version of httptransfer, which improves cases where an HTTP retry is required.
To improve the stability of very large file uploads.
Manual testing, unit tests pass, e2e tests pass.
- ~[ ] My change requires a change to the documentation.~
- ~[ ] I have updated the documentation accordingly.~
- ~[ ] I have added tests to cover my changes.~
=> update to latest version of http transfer to improve retry functionality

package-lock.json, package.json
The fix is in `@adobe/node-httptransfer`: https://github.com/adobe/node-httptransfer/pull/64
This PR pulls in the dependency update.
The PR has been tested manually, and through unit tests.
=> Fix mime-type handling in AEM uploads

src/constants.js
Changed the set of characters that are sanitized in a folder's name when uploading from local.
#56 
The behavior of the library is inconsistent with AEM' requirements.
Ran a test upload to ensure sanitization is correct. All unit tests pass.
N/A
=> correct characters that are sanitized in folder names

README.md, package-lock.json, package.json, src/direct-binary-upload-options.js, src/direct-binary-upload-process.js, src/upload-file.js, src/utils.js, test/upload-file.test.js, test/utils.test.js
This PR introduces a new feature that allows consumers to specify which headers should be included in requests that upload individual file parts. These are typically the requests that are sent to a data store like Azure.
In addition, this PR resolves a small issue with blobs as described in #55.
See #55 
For the resolution to #55, it means that the library can once again be used in the context of a browser.
For the part headers, there may be cases where a data store like Azure (or a CDN in between) rejects requests that don't include certain header information (such as a User Agent). This new option provides consumers with the ability to provide additional headers to these requests; this was not possible before.
Unit test run locally. Manual testing from a React application show that …
=> Add ability to specify headers to include in part uploads

package-lock.json, package.json
Updates to latest version of `node-httptransfer` to resolve issue where files with parens in the name fail to upload.
#65 
Parens are valid characters and should not be rejected.
* Manually tested
* Unit tests pass
* e2e tests pass
N/A
=> update node-httptransfer to allow parens in asset names.

e2e/e2eutils.js, e2e/filesystem-upload.test.js, src/direct-binary-upload-options.js, src/filesystem-upload-directory.js, src/init-response-file-info.js, test/direct-binary-upload-options.test.js, test/filesystem-upload-directory.test.js, test/init-response-file-info.test.js
There was an issue reported in AEM Desktop where the app would hang when trying to upload files or folders to a directory like `test中文`. Root cause of the issue was that the URL given to `aem-upload` was not URI encoded. However, upon properly encoding the URL, I identified problems within `aem-upload` itself. It's not handling encoding on incoming URLs as it should. There are more details in the related issue.
The fix itself was small - most of the changes in this PR are new unit tests and a new e2e test for verifying this case.
#72 
See related issue, but files/folders could not be uploaded to directories with characters requiring encoding.
* Manually linked the updated library to AEM Desktop locally, and verified that the issue was resolved. Also manually tested other common encoding …
=> fix issues when target URL contains encoded characters.

README.md, package-lock.json, package.json
Updates to the latest version of `node-httptransfer` so that the `uploadDuration` property is provided in finalize calls.
See related [node-httptransfer issue](https://github.com/adobe/node-httptransfer/issues/116) for details.
Allows calculation of transfer rates on AEM's end.
All unit tests and e2e tests pass. Verified that parameter value is provided in AEM logs.
N/A
=> Fix: include uploadDuration when uploading files.

src/constants.js, test/filesystem-upload-utils.test.js
Modifies the set of illegal characters so that periods are allowed in file names.
#79 
Some consumers of the module use dots in file names as part of their naming conventions. This brings the library's functionality inline with AEM's web UI.
New unit test, manually tested, tested through AEM desktop.
N/A
=> Fix: allow dots in file names.

README.md, package-lock.json, package.json, src/direct-binary-upload-options.js, src/direct-binary-upload-process.js, src/exports.js, src/filesystem-upload-options.js, src/http-proxy.js, src/http-utils.js, src/http/http-request.js, src/utils.js, test/direct-binary-upload-options.test.js, test/filesystem-upload-options.test.js, test/filesystem-upload.test.js, test/http-proxy.test.js, test/http-utils.test.js, test/http/http-request.test.js, test/utils.test.js
This PR adds a new `.withHttpProxy()` method that allows consumers to set information about the proxy that should be used for all requests sent during the upload process. This will include requests for creating directories (which is specific to `aem-upload`), and requests that upload files (which is handled by `node-httptransfer`).
Initially I was just going to add a more generic method like `withHttpOptions()`, which would just directly pass supplied options through to the underlying HTTP client. However, this became problematic because `node-httptransfer` uses `fetch`, whereas `aem-upload` uses `axios`. The complication of providing a single, shared set of generic options for both clients quickly became unintuitive. In the future we could standardize both libraries on a single client, …
=> Add proxy support

README.md, e2e/filesystem-upload.test.js, src/filesystem-upload.js, src/utils.js, test/filesystem-upload.test.js, test/testutils.js, test/utils.test.js
Makes the following changes to the filesystem upload process:
* Create folders in AEM even if they don't have files in them. This is a change in current functionality, and will warrant a new minor release.
* Send a new `foldercreated` event whenever the library creates a folder in AEM. Readme has also been updated with information about the new event.
* Don't call `node-httptransfer` if there are no files being uploaded.
* Update unit tests and e2e test to validate new functionality.
#86 
AEM Desktop uses this library when uploading local files. Before using `aem-upload`, the app would create all folders from the local structure in AEM, even if they were empty. To bring `aem-upload` inline with these requirements, it will be updated so that it no longer filters out empty directories.
In …
=> add foldercreated event. create folders even when empty

README.md, src/direct-binary-upload-process.js, src/direct-binary-upload.js, src/filesystem-upload.js, src/upload-base.js, test/direct-binary-upload-process.test.js, test/direct-binary-upload.test.js
Fixed `DirectBinaryUpload` so that it correctly sends `fileuploadstart` and `fileuploadend`. Both `DirectBinaryUpload` and `FileSystemUpload` now share code that ensures consistency of events between the two upload methods.
#93 
There's inconsistency between the events that are sent, depending on which method of uploading is used. This will bring the two branches into alignment.
* New unit tests
* Existing unit tests pass
* `e2e` tests pass
* Incorporated updated library into a client application and tested to ensure all events are sent as expected.
N/A
=> Send all events when uploading with DirectBinaryUpload

README.md, package-lock.json, package.json, src/direct-binary-upload.js, test/direct-binary-upload.test.js
`node-httptransfer` was recently updated so that it can upload to AEM instances that don't have direct binary upload enabled. In these cases, it will fall back to using the create asset servlet.
This PR updates to a version of `node-httptransfer` that supports "legacy" instances, and changes the behavior of this module when checking to see if it can upload to a target instance.
#95 
Now this module can be used to efficiently upload files to _any_ instance of AEM, not just those that have direct binary upload enabled. This will help simplify consumers of the library that might need to be able to upload to legacy AEM configurations; now these clients can use this single library and not need to come up with their own process for uploading files.
* Existing unit tests and e2e tests pass.
* …
=> Allow uploads to instances without direct binary upload

.github/workflows/node.js.yml
The semantic-release portion of the CI began failing after upgrading to the newest version of semantic-release. Root cause was that the release step was running on version 12 of node. Updated the step to run on version 18 instead.
N/A
Keeping dependencies updated.
N/A
N/A
=> fix node.js version on which semantic-release step runs

package-lock.json, package.json
See details on [node-httptransfer](https://github.com/adobe/node-httptransfer/issues/145). In summary, uploading to non-cloud AEM instances fails in some conditions. This PR fixes that issue.
See link above.
See link above.
Unit tests and e2e tests pass. Updating library locally and running a test passes.
N/A
=> update to latest node-httptransfer

e2e/e2eutils.js, package-lock.json, package.json, src/utils.js, test/direct-binary-upload-process.test.js, test/mock-aem-upload.js
This PR updates to the latest version of `node-httptransfer` so that request options (including proxy settings) are correctly sent with CORS requests.
N/A
Fixes the library to work correctly with proxy settings in all cases.
Unit tests and e2e tests pass.
N/A
=> fix: pass request options to cors requests

src/http-utils.js, test/filesystem-upload.test.js, test/http-utils.test.js
The process of creating directories already handles eventual consistency with the `cloud-service-client` library. However, requests to initiate and complete uploads are performed by `node-httptransfer`, which has its own library for overcoming eventual consistency. This PR translates the `cloud-service-client` option for eventual consistency into the equivalent `node-httptransfer` option.
#117 
As described in the associated ticket, this will help avoid failures in cases where directories are created then uploaded to in very fast succession.
New unit test added, existing unit tests pass, existing e2e tests pass.
N/A
=> improve support for handling eventual consistency when uploading.
